/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/auth/registration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_registration'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['AuthController_logout'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_refresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProfileController_getUserData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PublicMangaController_getMangaList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/last-updated': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PublicMangaController_getLastUpdatedMangas'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/related/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PublicMangaController_getRelatedManga'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/quick-search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['QuickSearchController_getMangaQuickSearch'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/quick-search/last': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['QuickSearchController_getUserLastSearchQueries'];
    put?: never;
    post?: never;
    delete: operations['QuickSearchController_deleteUserLastSearchQuery'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/continue-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ContinueReadMangaController_getContinueReadManga'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/continue-read/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ContinueReadMangaController_dontShowContinueReadManga'];
    trace?: never;
  };
  '/manga/edit/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EditMangaController_getEditedManga'];
    put: operations['EditMangaController_updateManga'];
    post?: never;
    delete: operations['EditMangaController_deleteManga'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/edit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['EditMangaController_createManga'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/edit/{id}/covers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EditMangaCoverController_getMangaCovers'];
    put?: never;
    post: operations['EditMangaCoverController_addMangaCovers'];
    delete: operations['EditMangaCoverController_deleteMangaCovers'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/byId/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IndividualMangaController_getManga'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/byId/{id}/covers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IndividualMangaController_getMangaCovers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/byId/{id}/bookmark': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookmarkController_getUserMangaBookmark'];
    put?: never;
    post?: never;
    delete: operations['BookmarkController_deleteUserMangaBookmark'];
    options?: never;
    head?: never;
    patch: operations['BookmarkController_setUserMangaBookmark'];
    trace?: never;
  };
  '/manga/byId/{id}/rate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RateController_getUserMangaRate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['RateController_setUserMangaRate'];
    trace?: never;
  };
  '/manga/genres': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MangaGenresController_getGenres'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MangaTagsController_getTags'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/statistic/{id}/rate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MangaStatisticController_getRateStatistic'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/statistic/{id}/bookmark': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MangaStatisticController_getBookmarkStatistic'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/chapter/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PublicChapterController_getChapter'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/{mangaId}/chapters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PublicChapterController_getChapterList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/chapter/{id}/like': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ChapterActionController_setUserLikeChapter'];
    trace?: never;
  };
  '/manga/chapter/{id}/view': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ChapterActionController_setUserViewChapter'];
    trace?: never;
  };
  '/manga/edit/{mangaId}/chapter/{chapterId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EditChapterController_getEditedChapter'];
    put: operations['EditChapterController_updateChapter'];
    post?: never;
    delete: operations['EditChapterController_deleteChapter'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/edit/{mangaId}/chapter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EditChapterController_getEditedChapterList'];
    put?: never;
    post: operations['EditChapterController_createChapter'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/edit/{mangaId}/chapter/{chapterId}/pages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EditChapterPagesController_getChapterPages'];
    put: operations['EditChapterPagesController_setChapterPages'];
    post: operations['EditChapterPagesController_addPage'];
    delete: operations['EditChapterPagesController_deletePage'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/manga/edit/{mangaId}/chapter/{chapterId}/pages/lang': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['EditChapterPagesController_addLangChapterPages'];
    delete: operations['EditChapterPagesController_deleteLangChapterPages'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    CreateUserDto: {
      login: string;
      password: string;
    };
    LoginUserDto: {
      login: string;
      password: string;
    };
    DeleteSearchDto: {
      search: string;
    };
    MutateMangaDto: {
      urlId?: string;
      title?: {
        ru?: string;
        en?: string;
        origin?: string;
      };
      otherTitles?: {
        createTitles?: string[];
        updateTitles?: {
          id: number;
          title: string;
        }[];
        deleteTitles?: number[];
      };
      description?: {
        ru?: string;
        en?: string;
      };
      /** @enum {string} */
      status?: 'Ongoing' | 'Announced' | 'Completed' | 'Frozen' | 'Canceled';
      /** @enum {string} */
      type?: 'Manga' | 'Manhwa' | 'Manhua' | 'OEL' | 'Rumanga' | 'Comic';
      /** Format: date-time */
      releaseDate?: string;
      genres?: {
        add?: number[];
        delete?: number[];
        set?: number[];
      };
      tags?: {
        add?: number[];
        delete?: number[];
        set?: number[];
      };
      coverId?: number;
      banner?: string;
      ageRate: number;
      authors?: {
        add?: string[];
        delete?: number[];
      };
      artists?: {
        add?: string[];
        delete?: number[];
      };
      publishers?: {
        add?: string[];
        delete?: number[];
      };
    };
    DeleleMangaCoversDto: {
      coversId: unknown[][];
    };
    BookmarkDto: {
      /** @enum {string} */
      bookmark: 'Reading' | 'Planned' | 'Readed' | 'Abandoned' | 'Postponed';
    };
    SetUserMangaRateDto: {
      rate: number;
    };
    MutateChapterDto: {
      title?: {
        ru?: string;
        en?: string;
      };
      tome?: number;
      chapter?: number;
      private?: boolean;
    };
    ChapterPagesDto: {
      pageCount: number;
      /** @default 700 */
      containerMaxWidth: number;
      pages: unknown[][];
    };
    LangQueryDto: {
      /**
       * @default ru
       * @enum {string}
       */
      lang: 'ru' | 'en';
    };
    DeleteChapterPageDto: {
      pageSrc: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  AuthController_registration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "user": {
           *         "sub": 1,
           *         "id": 1,
           *         "name": "name",
           *         "login": "login"
           *       },
           *       "tokens": {
           *         "access": "access",
           *         "refresh": "refresh"
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "user": {
           *         "sub": 1,
           *         "id": 1,
           *         "name": "name",
           *         "login": "login"
           *       },
           *       "tokens": {
           *         "access": "access",
           *         "refresh": "refresh"
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "user": {
           *         "sub": 1,
           *         "id": 1,
           *         "name": "name",
           *         "login": "login"
           *       },
           *       "tokens": {
           *         "access": "access",
           *         "refresh": "refresh"
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  ProfileController_getUserData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User id get from token */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 1,
           *       "name": "becki",
           *       "avatar": "http://wrondway.com",
           *       "jsonSettings": {}
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  PublicMangaController_getMangaList: {
    parameters: {
      query?: {
        sortBy?:
          | 'rating'
          | 'updateDate'
          | 'createDate'
          | 'ruAlphabetically'
          | 'enAlphabetically'
          | 'views'
          | 'likes'
          | 'chapterCount';
        search?: string;
        genres?: string;
        tags?: string;
        notGenres?: string;
        notTags?: string;
        status?: string;
        type?: string;
        bookmarks?: string;
        lang?: 'ru' | 'en';
        order?: 'asc' | 'desc';
        page?: number;
        limit?: number;
        ageRateFrom?: number;
        ageRateTo?: number;
        chapterCountFrom?: number;
        chapterCountTo?: number;
        rateCountFrom?: number;
        rateCountTo?: number;
        rateFrom?: number;
        rateTo?: number;
        releaseDateFrom?: string;
        releaseDateTo?: string;
        /** @description Comma-separated list of  IDs, e.g. genres=1,3,4 */
        'genres-tags-notGenres-notTags'?: unknown;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "cover": "http://wrong-way.com",
           *           "chapterCount": 45,
           *           "bookmark": null,
           *           "rate": 10,
           *           "type": "Manga"
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "cover": "http://wrong-way.com",
           *           "chapterCount": 45,
           *           "bookmark": null,
           *           "rate": 10,
           *           "type": "Manga"
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "cover": "http://wrong-way.com",
           *           "chapterCount": 45,
           *           "bookmark": null,
           *           "rate": 10,
           *           "type": "Manga"
           *         }
           *       ],
           *       "prevPage": null,
           *       "nextPage": null
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  PublicMangaController_getLastUpdatedMangas: {
    parameters: {
      query?: {
        scope?: 'all' | 'popular' | 'my';
        lang?: 'ru' | 'en';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description scope 'my' for authorized users only */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "tome": 1,
           *           "chapter": 2,
           *           "chapterCreatedAt": "2025-05-14T08:32:11.444Z",
           *           "chapterId": 0
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "tome": 1,
           *           "chapter": 2,
           *           "chapterCreatedAt": "2025-05-14T08:32:11.444Z",
           *           "chapterId": 0
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "tome": 1,
           *           "chapter": 2,
           *           "chapterCreatedAt": "2025-05-14T08:32:11.444Z",
           *           "chapterId": 0
           *         }
           *       ],
           *       "prevPage": null,
           *       "nextPage": null
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  PublicMangaController_getRelatedManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  QuickSearchController_getMangaQuickSearch: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Automaticly save user search */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "some-manga---1234",
           *           "title": "Manga title",
           *           "type": "Manga",
           *           "cover": "http://wrong-way.com",
           *           "views": 100,
           *           "likes": 10,
           *           "bookmarks": 1
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  QuickSearchController_getUserLastSearchQueries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         "search",
           *         "search2"
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  QuickSearchController_deleteUserLastSearchQuery: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteSearchDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContinueReadMangaController_getContinueReadManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "chapter": 5,
           *           "chapterCount": 88,
           *           "tome": 1,
           *           "readedChapters": 5,
           *           "cover": "http://wrong-way.com",
           *           "chapterId": 0
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "chapter": 5,
           *           "chapterCount": 88,
           *           "tome": 1,
           *           "readedChapters": 5,
           *           "cover": "http://wrong-way.com",
           *           "chapterId": 0
           *         },
           *         {
           *           "id": 1,
           *           "urlId": "same-manga---1234",
           *           "title": "Manga Title",
           *           "chapter": 5,
           *           "chapterCount": 88,
           *           "tome": 1,
           *           "readedChapters": 5,
           *           "cover": "http://wrong-way.com",
           *           "chapterId": 0
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  ContinueReadMangaController_dontShowContinueReadManga: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description set id to 0 to delete all manga */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EditMangaController_getEditedManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "urlId": "some-url-id---0",
           *       "title": {
           *         "ru": "undefined",
           *         "en": null,
           *         "origin": null
           *       },
           *       "otherTitles": [
           *         {
           *           "id": 1,
           *           "title": "title1"
           *         }
           *       ],
           *       "description": {
           *         "ru": "description",
           *         "en": null
           *       },
           *       "releaseDate": null,
           *       "status": "Ongoing",
           *       "type": "Manga",
           *       "genres": [
           *         {
           *           "id": 1,
           *           "title": "Horror"
           *         }
           *       ],
           *       "tags": [
           *         {
           *           "id": 1,
           *           "title": "Magic"
           *         }
           *       ],
           *       "covers": [
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com",
           *           "main": true
           *         }
           *       ],
           *       "banner": "http://wrong-way.com",
           *       "ageRate": 0,
           *       "authors": [
           *         {
           *           "id": 1,
           *           "name": "author"
           *         }
           *       ],
           *       "artists": [
           *         {
           *           "id": 1,
           *           "name": "artist"
           *         }
           *       ],
           *       "publishers": [
           *         {
           *           "id": 1,
           *           "name": "publisher"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditMangaController_updateManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description 1 баннер (формат — файл) */
          banner?: string[];
          body?: components['schemas']['MutateMangaDto'];
        };
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "urlId": "some-url-id---0",
           *       "title": {
           *         "ru": "undefined",
           *         "en": null,
           *         "origin": null
           *       },
           *       "otherTitles": [
           *         {
           *           "id": 1,
           *           "title": "title1"
           *         }
           *       ],
           *       "description": {
           *         "ru": "description",
           *         "en": null
           *       },
           *       "releaseDate": null,
           *       "status": "Ongoing",
           *       "type": "Manga",
           *       "genres": [
           *         {
           *           "id": 1,
           *           "title": "Horror"
           *         }
           *       ],
           *       "tags": [
           *         {
           *           "id": 1,
           *           "title": "Magic"
           *         }
           *       ],
           *       "covers": [
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com",
           *           "main": true
           *         }
           *       ],
           *       "banner": "http://wrong-way.com",
           *       "ageRate": 0,
           *       "authors": [
           *         {
           *           "id": 1,
           *           "name": "author"
           *         }
           *       ],
           *       "artists": [
           *         {
           *           "id": 1,
           *           "name": "artist"
           *         }
           *       ],
           *       "publishers": [
           *         {
           *           "id": 1,
           *           "name": "publisher"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditMangaController_deleteManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EditMangaController_createManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description 1 обложка (формат — файл) */
          covers?: string[];
          /** @description 1 баннер (формат — файл) */
          banner?: string[];
          body?: components['schemas']['MutateMangaDto'];
        };
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "urlId": "some-url-id---0",
           *       "title": {
           *         "ru": "undefined",
           *         "en": null,
           *         "origin": null
           *       },
           *       "otherTitles": [
           *         {
           *           "id": 1,
           *           "title": "title1"
           *         }
           *       ],
           *       "description": {
           *         "ru": "description",
           *         "en": null
           *       },
           *       "releaseDate": null,
           *       "status": "Ongoing",
           *       "type": "Manga",
           *       "genres": [
           *         {
           *           "id": 1,
           *           "title": "Horror"
           *         }
           *       ],
           *       "tags": [
           *         {
           *           "id": 1,
           *           "title": "Magic"
           *         }
           *       ],
           *       "covers": [
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com",
           *           "main": true
           *         }
           *       ],
           *       "banner": "http://wrong-way.com",
           *       "ageRate": 0,
           *       "authors": [
           *         {
           *           "id": 1,
           *           "name": "author"
           *         }
           *       ],
           *       "artists": [
           *         {
           *           "id": 1,
           *           "name": "artist"
           *         }
           *       ],
           *       "publishers": [
           *         {
           *           "id": 1,
           *           "name": "publisher"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditMangaCoverController_getMangaCovers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         },
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         },
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditMangaCoverController_addMangaCovers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description До 5 изображений обложек (формат — файл) */
          covers?: string[];
        };
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         },
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         },
           *         {
           *           "id": 0,
           *           "cover": "http://wrong-way.com",
           *           "main": false
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditMangaCoverController_deleteMangaCovers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleleMangaCoversDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  IndividualMangaController_getManga: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 1,
           *       "urlId": "some-url-id---123",
           *       "title": {
           *         "ru": "ru-Title",
           *         "en": "en-Title",
           *         "origin": "original-Title"
           *       },
           *       "otherTitles": [
           *         "Другое название",
           *         "otherTitle2",
           *         "otherTitle3"
           *       ],
           *       "description": "some manga description",
           *       "chaptersCount": 45,
           *       "rate": 9.8,
           *       "countRate": 201,
           *       "releaseDate": "2025-05-14T08:32:16.887Z",
           *       "status": "Ongoing",
           *       "type": "Manga",
           *       "genres": [
           *         {
           *           "id": 1,
           *           "title": "Horror"
           *         },
           *         {
           *           "id": 2,
           *           "title": "Романтика"
           *         }
           *       ],
           *       "tags": [
           *         {
           *           "id": 1,
           *           "title": "Магия"
           *         }
           *       ],
           *       "cover": "http://wrong-way.com",
           *       "banner": "http://wrong-way.com",
           *       "owner": {
           *         "id": 1,
           *         "name": "wendsew",
           *         "avatar": "http://wrong-way.com"
           *       },
           *       "authors": [
           *         "wendsew"
           *       ],
           *       "artists": [
           *         "wendsew"
           *       ],
           *       "publishers": [
           *         "HikiUda"
           *       ],
           *       "bookmark": null
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  IndividualMangaController_getMangaCovers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com"
           *         },
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com"
           *         },
           *         {
           *           "id": 1,
           *           "cover": "http://wrong-way.com"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  BookmarkController_getUserMangaBookmark: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "mangaId": 2,
           *       "userId": 1,
           *       "bookmark": "Abandoned"
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  BookmarkController_deleteUserMangaBookmark: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookmarkController_setUserMangaBookmark: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BookmarkDto'];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "mangaId": 2,
           *       "userId": 1,
           *       "bookmark": "Abandoned"
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  RateController_getUserMangaRate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "rate": 9,
           *       "mangaId": 2,
           *       "userId": 1
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  RateController_setUserMangaRate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetUserMangaRateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "rate": 9,
           *       "mangaId": 2,
           *       "userId": 1
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  MangaGenresController_getGenres: {
    parameters: {
      query?: {
        search?: string;
        lang?: 'ru' | 'en';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         },
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         },
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  MangaTagsController_getTags: {
    parameters: {
      query?: {
        search?: string;
        lang?: 'ru' | 'en';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         },
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         },
           *         {
           *           "id": 0,
           *           "title": "Category"
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  MangaStatisticController_getRateStatistic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "rate": 0,
           *       "rateCount": 0,
           *       "rateStatistic": [
           *         {
           *           "title": "1",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "2",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "3",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "4",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "5",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "6",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "7",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "8",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "9",
           *           "count": 0,
           *           "percentage": 0
           *         },
           *         {
           *           "title": "10",
           *           "count": 0,
           *           "percentage": 0
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  MangaStatisticController_getBookmarkStatistic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description urlId or just id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "all": 100,
           *       "bookmarks": [
           *         {
           *           "title": "Reading",
           *           "count": 20,
           *           "percentage": 20
           *         },
           *         {
           *           "title": "Planned",
           *           "count": 10,
           *           "percentage": 10
           *         },
           *         {
           *           "title": "Readed",
           *           "count": 50,
           *           "percentage": 50
           *         },
           *         {
           *           "title": "Abandoned",
           *           "count": 15,
           *           "percentage": 15
           *         },
           *         {
           *           "title": "Postponed",
           *           "count": 5,
           *           "percentage": 5
           *         }
           *       ]
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  PublicChapterController_getChapter: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 2,
           *       "tome": 1,
           *       "chapter": 2,
           *       "title": "chapter title",
           *       "mangaTitle": "Manga Title",
           *       "likeCount": 100,
           *       "pages": {
           *         "pageCount": 1,
           *         "pages": [
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           }
           *         ],
           *         "containerMaxWidth": 700
           *       },
           *       "isUserLiked": false,
           *       "isUserViewed": false,
           *       "prevChapterId": 1,
           *       "nextChapterId": 3
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  PublicChapterController_getChapterList: {
    parameters: {
      query?: {
        search?: string;
        lang?: 'ru' | 'en';
        page?: number;
        limit?: number;
        order?: 'asc' | 'desc';
      };
      header?: never;
      path: {
        mangaId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.928Z",
           *           "isUserViewed": false
           *         },
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.928Z",
           *           "isUserViewed": false
           *         },
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.928Z",
           *           "isUserViewed": false
           *         }
           *       ],
           *       "prevPage": null,
           *       "nextPage": null
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  ChapterActionController_setUserLikeChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ChapterActionController_setUserViewChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EditChapterController_getEditedChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "title": {
           *         "ru": "Ru title",
           *         "en": "En Title"
           *       },
           *       "tome": 1,
           *       "chpater": 2,
           *       "private": false,
           *       "mangaId": 0
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterController_updateChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MutateChapterDto'];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "title": {
           *         "ru": "Ru title",
           *         "en": "En Title"
           *       },
           *       "tome": 1,
           *       "chpater": 2,
           *       "private": false,
           *       "mangaId": 0
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterController_deleteChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EditChapterController_getEditedChapterList: {
    parameters: {
      query?: {
        search?: string;
        lang?: 'ru' | 'en';
        page?: number;
        limit?: number;
        order?: 'asc' | 'desc';
      };
      header?: never;
      path: {
        mangaId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "data": [
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.948Z",
           *           "private": true
           *         },
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.948Z",
           *           "private": true
           *         },
           *         {
           *           "id": 0,
           *           "tome": 1,
           *           "chapter": 2,
           *           "title": null,
           *           "createdAt": "2025-05-14T08:32:16.948Z",
           *           "private": true
           *         }
           *       ],
           *       "prevPage": null,
           *       "nextPage": null
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterController_createChapter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MutateChapterDto'];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": 0,
           *       "title": {
           *         "ru": "Ru title",
           *         "en": "En Title"
           *       },
           *       "tome": 1,
           *       "chpater": 2,
           *       "private": false,
           *       "mangaId": 0
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterPagesController_getChapterPages: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "pageCount": 3,
           *       "pages": [
           *         {
           *           "src": "pass/pass/pass.jpg",
           *           "type": "image"
           *         },
           *         {
           *           "src": "pass/pass/pass.jpg",
           *           "type": "image"
           *         },
           *         {
           *           "src": "pass/pass/pass.jpg",
           *           "type": "rive"
           *         }
           *       ],
           *       "containerMaxWidth": 700
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterPagesController_setChapterPages: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChapterPagesDto'];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "mockChapterPages": {
           *         "pageCount": 3,
           *         "pages": [
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "rive"
           *           }
           *         ],
           *         "containerMaxWidth": 700
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterPagesController_addPage: {
    parameters: {
      query?: {
        returnValue?: boolean;
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description Одна страница за раз (формат — файл) */
          page?: string[];
        };
      };
    };
    responses: {
      /** @description Возвращает данные в ответе только если returnValue=true */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "mockChapterPages": {
           *         "pageCount": 3,
           *         "pages": [
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "rive"
           *           }
           *         ],
           *         "containerMaxWidth": 700
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterPagesController_deletePage: {
    parameters: {
      query?: {
        lang?: 'ru' | 'en';
      };
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteChapterPageDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EditChapterPagesController_addLangChapterPages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LangQueryDto'];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "mockChapterPages": {
           *         "pageCount": 3,
           *         "pages": [
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "image"
           *           },
           *           {
           *             "src": "pass/pass/pass.jpg",
           *             "type": "rive"
           *           }
           *         ],
           *         "containerMaxWidth": 700
           *       }
           *     } */
          'application/json': unknown;
        };
      };
    };
  };
  EditChapterPagesController_deleteLangChapterPages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mangaId: string;
        chapterId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LangQueryDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
