/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/todo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить список всех задач */
    get: {
      parameters: {
        query?: {
          /** @description Поиск по названию задачи */
          search?: string;
          /** @description Фильтр по статусу выполнения */
          completed?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Успешный ответ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example [
             *       {
             *         "id": 1,
             *         "title": "Купить молоко",
             *         "completed": false
             *       },
             *       {
             *         "id": 2,
             *         "title": "Сделать домашку",
             *         "completed": true
             *       }
             *     ] */
            'application/json': components['schemas']['TodoItem'][];
          };
        };
      };
    };
    put?: never;
    /** Создать новую задачу */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /** @example {
           *       "title": "Новая задача",
           *       "completed": false
           *     } */
          'application/json': components['schemas']['TodoCreate'];
        };
      };
      responses: {
        /** @description Задача создана */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TodoItem'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/todo/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Обновить задачу */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          /** @example {
           *       "title": "Обновлённая задача",
           *       "completed": true
           *     } */
          'application/json': components['schemas']['TodoUpdate'];
        };
      };
      responses: {
        /** @description Задача обновлена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TodoItem'];
          };
        };
      };
    };
    post?: never;
    /** Удалить задачу */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Задача удалена */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TodoItem: {
      /** Format: int64 */
      id: number;
      title: string;
      completed: boolean;
    };
    TodoCreate: {
      title: string;
      /** @default false */
      completed: boolean;
    };
    TodoUpdate: {
      title: string;
      completed: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
